# Generated by Django 5.2.1 on 2025-07-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='ai_model',
        ),
    ]
